export * from './Hero';
export * from './Navbar';
export * from './Socials';
export * from './About';
export * from './Technologies';
export * from './WorkExperience';
export * from './PastWorks';
export * from './Contact';
export * from './Footer';
